In [3]:
import pandas as pd
import requests as r

In [4]:
df = pd.read_json('flood.json')

In [5]:
locations = [i['location'] for i in df['result']]

In [6]:
locations

['Far Rockaway Beach, NY 11691',
 'Far Rockaway Beach, NY 11691',
 'Far Rockaway Beach, NY 11691',
 'Far Rockaway Beach, NY 11691',
 'Far Rockaway Beach, NY 11691',
 'Far Rockaway Beach, NY 11691',
 'Far Rockaway Beach, NY 11691',
 'Far Rockaway Beach, NY 11691',
 'Far Rockaway Beach, NY 11691',
 'Harworth, England',
 'Oppresive States of Hellmerica',
 'Alaska & Sweden',
 'UK',
 'UK',
 'UK',
 'Harrogate District',
 '',
 'UK',
 'New York City',
 'Bangui',
 'Nigeria',
 '',
 'Iowa',
 'Far Rockaway Beach, NY 11691',
 'Far Rockaway Beach, NY 11691',
 'Far Rockaway Beach, NY 11691',
 'Far Rockaway Beach, NY 11691',
 'Far Rockaway Beach, NY 11691',
 'Toronto, Ontario',
 'Far Rockaway Beach, NY 11691',
 'Far Rockaway Beach, NY 11691',
 'Worldwide',
 'Far Rockaway Beach, NY 11691',
 '',
 'Oregon',
 'USA',
 'Delft, Nederland',
 'The Woodlands, TX',
 'Nairobi, Kenya',
 'UK',
 'Bridport, England',
 'sheffield',
 'West Coast, Canada',
 'Cameroon',
 'Zürich',
 'Planet Earth',
 'Phoenix, AZ',
 '',
 'Los Angeles, CA',
 'Athens, Greece',
 '',
 'Tallahassee, FL',
 'South Africa',
 'Long Island City, New York',
 'Paris, France',
 'United Kingdom',
 '',
 'Cheshire, UK',
 'Somalia',
 '0800 331 7070',
 '',
 'Planet Earth,Japan',
 'USA',
 'Nottingham, England',
 'Gujarat',
 'United Kingdom - Djibouti ',
 '#AFRICA #MENA',
 'Worcester',
 'Zurich, Switzerland',
 'France',
 'Oxfordshire',
 'Rugby, England',
 'Madison, Wisconsin, USA',
 '',
 'USA',
 'Yorkshire, England',
 'Yorkshire, England',
 'Worcester, England',
 'Bengaluru, India',
 'Somalia',
 'United Kingdom',
 'Mumbai',
 'Zurich, Switzerland',
 'Nairobi, Kenya',
 'Reading, England',
 'USA',
 'South West, England',
 'Warwickshire',
 'Kenya',
 '',
 'Bengaluru, India',
 'Terrace, British Columbia',
 'USA',
 'Lagos, Nigeria',
 'Sydney🇦🇺',
 'Ankara, Türkiye',
 'USA/Canada',
 'Bengaluru, India',
 'India',
 'New York, USA',
 'NY',
 '',
 'USA',
 'British Columbia, Canada',
 'Trinidad and Tobago',
 '',
 'Global',
 'New York, USA',
 'NY',
 'mumbai',
 'Toronto, Canada',
 'Australia',
 'Nigeria',
 '',
 'USA',
 'Brussels',
 '',
 'South West, England',
 'Evesham Worcester uk',
 'Evesham Worcester uk',
 'South West, England',
 '',
 'Cork',
 '',
 'New York, USA',
 'NY',
 'Barcelona, Catalonia',
 'West Coast, Canada',
 'somaliland',
 'Mumbai/Bangalore/Jodhpur',
 'Malta',
 'Lewisburg, TN',
 'United States',
 'England',
 'England',
 'New Delhi - India',
 'New Delhi, Delhi',
 'Bengaluru South, India',
 'USA',
 'Northern California USA',
 '',
 'Saint Louis',
 'International',
 '',
 '',
 'National Capital Region',
 'Planet Earth,Japan',
 'This is an official account',
 'London',
 'Manhattan, NY',
 'Great Rollright, England',
 'USA',
 'Kenya',
 'Central England',
 'Thailand',
 'UK',
 'New Delhi - India',
 'Beverley, East Yorkshire',
 'Devon England',
 'Hargeisa, Somaliland',
 'tehran.iran',
 'Hyderabad, India',
 'From all over the planet',
 'Error 451',
 'Australia  ',
 'Minneapolis, MN',
 'Nairobi, Kenya',
 'Nairobi, Kenya',
 'Worldwide',
 'New York, USA',
 'NY',
 'West Coast, Canada',
 'USA',
 'USA',
 'Moskau',
 'Yorkshire/Cumbria/NorthEast',
 'New Delhi - India',
 '',
 'Cheltenham',
 '',
 'Bangkok, Thailand',
 'USA',
 'Nairobi, Kenya',
 'Nairobi, Kenya',
 'Winchester, Hampshire, UK',
 'Worcestershire, UK',
 'Europe, Belgium',
 'Manhattan, NY',
 'Europe, Belgium',
 'Sacramento, CA',
 'Europe, Belgium',
 'Washington, DC',
 'England',
 'USA',
 'INDIA',
 'Contact us on 01935 709735 or via newsdesk@westgaz.co.uk',
 'Chesterfield, England',
 'Yorkshire/Cumbria/NorthEast',
 '',
 'Yorkshire',
 'UK  Notts.',
 'York',
 'Bath, UK',
 'England',
 'United Kingdom',
 'New Delhi',
 'GreenAid-Africa',
 '',
 'USA',
 'South West, England',
 '',
 '',
 'Europe',
 '',
 'England, United Kingdom',
 'West Midlands, England',
 'Norwich, England',
 'West Midlands, England',
 'London',
 'Contact us on 01935 709735 or via newsdesk@westgaz.co.uk',
 'Nairobi, Kenya',
 'North Herts, UK',
 'Contact us on 01935 709735 or via newsdesk@westgaz.co.uk',
 ' England',
 'Juba',
 'USA',
 'Juba, South Sudan',
 'USA',
 'USA',
 'Centerville, Ohio 45459',
 'Horsham, PA',
 'Yorkshire & HHLs',
 'Worldwide (Global Citizen)',
 'Worthing / Brighton',
 'Oakland, CA',
 'bondi',
 'South West, England',
 'Wakiso, Uganda',
 'Doncaster, England',
 'USA',
 'Enstone Airfield',
 'CA - CO - NOLA - MSP - DC - NY',
 'Tkaronto | Turtle Island',
 'Exeter, England',
 'London, England',
 'Boston',
 '',
 'Derbyshire',
 'Florida',
 'Sacramento, California',
 'USA',
 'England, United Kingdom',
 'Dorset, UK',
 'Yorkshire/Cumbria/NorthEast',
 'USA',
 '',
 'Nebraska USA',
 'Derbyshire UK',
 'Shrewsbury, Shropshire',
 'Noida, India',
 'London',
 'Gainsborough, England',
 '',
 'Thane, India',
 'Outlands and Badlands',
 'Hexham',
 'Winnipeg, Manitoba',
 'USA',
 '',
 'Portsmouth, UK',
 'The Earth',
 '',
 'Toronto, Ontario',
 '',
 'UK',
 'Bournemouth, England',
 'Tipperary, Ireland',
 '',
 '#AFRICA #MENA',
 '#AFRICA #MENA',
 '',
 'Geneva',
 'South West, England',
 'Cotswolds',
 '',
 'USA',
 'Newcastle, Co. Tipperary.',
 '',
 'Doncaster, England',
 'England, United Kingdom',
 'London',
 'Oxford, England',
 'London',
 'Islamabad',
 'Worcestershire, UK',
 'Global',
 'Global',
 'Stoke-on-Trent, England',
 'Nether Wallop, England',
 'India',
 'Durban, South Africa',
 'South Africa',
 'Virgo Supercluster, he',
 'Virgo Supercluster, he',
 'USA',
 'INDIA',
 'Long Island',
 'Sacramento, California',
 'California ',
 'Richmond VA',
 'Brussel, België',
 'Maryland, USA',
 'Geneva, Switzerland',
 'Richmond VA',
 'Worldwide',
 'Washington, DC',
 'Chesterfield, England',
 'Ghana & the World',
 'Worcestershire',
 'West Yorkshire',
 'Chesterfield, England',
 'Pleasanton, CA',
 'UK',
 'Harworth, England',
 'Menlo Park, CA',
 'Houston, TX',
 'England, United Kingdom',
 'Plymouth United Kingdom',
 'Lucknow, India',
 'Bangui',
 'https://eastafricamonitor.com/',
 'UK - ENGLAND',
 'Global',
 'Accra / Africa',
 'London',
 'San Francisco, CA',
 'Venezia, Veneto',
 'London Borough of Enfield',
 'Manchester, England',
 'London',
 '',
 'Dublin City, Ireland',
 'Darlington, England',
 'National',
 '',
 'USA',
 'Ireland',
 '',
 'London & Yorkshire Pennines',
 'London, UK',
 '',
 'UK',
 'London & Yorkshire Pennines',
 '',
 'Nord, Cameroon',
 'Bradford, England',
 'Yorkshire',
 '',
 '',
 'Hillingdon, London',
 'Paris, France',
 'crewe',
 '',
 'Harworth, England',
 '',
 'London, UK',
 'United Kingdom',
 'Wales, United Kingdom',
 'Australia',
 'USA',
 '',
 '',
 'Yorkshire',
 'UK',
 'India',
 'New Delhi, India',
 '',
 'Saint Lucia',
 'North Derbyshire',
 '',
 'Los Angeles, CA',
 'USA',
 'Where’s my muffin at 🌚',
 'Berkeley, CA',
 'Madison, Wisconsin, USA',
 '',
 'USA',
 'USA',
 'Sri Lanka',
 'Tempe, AZ',
 'Harworth, England',
 'United States',
 'chennai',
 'Coachella Valley/Palm Springs',
 'Southwest Florida',
 'Leeds, UK',
 'Up North Planet Earth',
 'All across the UK',
 'NZ . East BOP',
 'New York, USA',
 'NY',
 'Manitoba',
 '',
 '',
 'Cochin, India',
 '',
 '',
 'Southern California',
 'Los Angeles, CA',
 'UK',
 'LV USA',
 'Harworth, England',
 'Kendal, Cumbria, UK',
 'South West, England',
 'Cornwall - UK',
 'Yorkshire',
 '',
 'Baltimore, MD',
 'Doncaster, England',
 'London, England',
 'North Nottinghamshire',
 'THE NORTH !',
 'The Southwest Trinity Worlds',
 'New York, USA',
 'NY',
 'Democratic Republic of Congo',
 'Long Eaton',
 'UK London Paris Europe ',
 'Aran Valley',
 'Worthington/Columbus/Urbana',
 '',
 'Los Angeles, CA',
 '',
 'Phoenix, AZ',
 'Firepool , Nkandla ',
 'CHINA',
 '',
 'USA',
 'England',
 'Leeds',
 '',
 'Yorkshire and The Humber',
 'Leicestershire',
 'UK',
 'England, UK.',
 '',
 'England',
 'Cotswolds & SW France',
 'London, England',
 'UK',
 'USA',
 'Ilkley',
 'Brisbane',
 '0118 9690 839',
 'Leeds/York/Newcastle',
 'ThirdRockFromTheSun',
 '🇵🇹🇪🇺',
 '',
 'London, England',
 'Hollyweird, CA',
 'Portsmouth, England',
 'USA',
 '',
 'The North East of England',
 'Oxfordshire',
 '',
 'Nairobi, Kenya',
 'Nairobi, Kenia',
 'USA',
 'Nairobi, Kenia',
 'Gurgaon, Haryana',
 'Mogadishu',
 'USA',
 'Global',
 'Global',
 'Serbia , Belgrade',
 'Global',
 'USA',
 'Kuala Lumpur, Malaysia',
 'pune',
 '',
 'USA',
 'Worcester, England',
 'Lincoln, NE 68508',
 '',
 'Cotswolds & SW France',
 'THE NORTH !',
 'Lincolnshire - UK',
 'en route 2 Heaven ~',
 'Worldwide',
 'Horsham, Victoria',
 'USA',
 'Cairns, Queensland',
 'Newport, Gwent',
 'United States',
 '',
 'Elk Grove Village, IL',
 'Troy, Michigan',
 'Mohali, India',
 'England, United Kingdom',
 'Chesterfield, England',
 '',
 'Oxford, England',
 'Helsingborg, Skåne Sweden',
 '',
 'Derbyshire',
 'England',
 'Derbyshire, UK',
 'National Office',
 '',
 '',
 'Derbyshire, UK',
 'New York, USA',
 'NY',
 'Stratford Upon Avon',
 'Auckley, Doncaster, DN9 3GG',
 'USA',
 'around Worcestershire',
 'Arizona',
 '',
 'Mohali, India',
 'Paris',
 'Yorkshire',
 '',
 'Worcester, England',
 'Leeds, England',
 '',
 'Cambridge, England',
 '',
 'Bassetlaw, Nottinghamshire',
 'Earth',
 'Mumbai, India',
 'UK - ENGLAND',
 'European Union',
 'Madison, Wisconsin, USA',
 '',
 'Stockholm, Sweden ',
 'One girl & her dog out walking',
 'Nigeria',
 'USA',
 'England, United Kingdom',
 'Doncaster, England',
 'Nairobi, Kenya',
 'New Delhi, India',
 'UK',
 'Derbyshire, UK',
 'worldwide',
 'Bonn, Germany',
 '🔴⚪️ ⚔️ Part of Sheffield',
 'West Midlands',
 'York, UK',
 '',
 'Yorkshire Post, Leeds',
 'Hamburgo, Alemania',
 'Yorkshire',
 'British Columbia, Canada',
 'Yorkshire',
 'Louisiana, USA',
 'San Francisco Bay Area',
 'USA',
 'South Sudan',
 'Patna, India',
 'USA',
 'Akron/Ohio',
 '',
 'Commerce City CO',
 'Hyderabad, India',
 'USA',
 'USA',
 'Las Vegas, NV',
 'UK',
 'UK',
 'UK',
 'Cotswolds & SW France',
 '',
 'Wooler, England',
 'Earth',
 'New York, USA',
 'NY',
 '',
 'London',
 'Ottawa, Kansas',
 'So. Cal.',
 'All over the show.',
 'Gloucestershire, England, UK',
 'Melbourne, Victoria',
 'Melbourne, Victoria',
 'Worcester, England',
 '',
 'Chelsea, London, England',
 '',
 'Honolulu, HI',
 '',
 'Toronto, Ontario',
 'British 🇬🇧 European 🇪🇺',
 'Pakistan',
 'Sheffield, South Yorkshire',
 '',
 '',
 'Mississauga, Ontario',
 'Newburyport, MA',
 'Yorkshire',
 'London',
 'Seattle, WA',
 '',
 'West Mids',
 'Newcastle Upon Tyne',
 'Chandigarh,India',
 'West Yorkshire, uk',
 'England',
 'Cardiff, Wales',
 'London',
 'Still in the EU',
 'United Kingdom',
 'US North Central Region',
 'South West London, UK',
 '',
 'United Kingdom',
 'Stoke-on-Trent, England',
 '',
 '',
 'England',
 '',
 'Stevenage',
 'Cybertron',
 'Cornwall & Middlesex ',
 'Harwell Campus, England',
 'Los Angeles',
 'Lurgan',
 'USA',
 'Edinburgh, Scotland',
 'Dublin City, Ireland',
 'ÜT: 51.49787,-0.024932',
 'Doncaster',
 '',
 'Worthing, West Sussex, England',
 'near Guildford',
 'Canterbury, UK',
 'Leominster, England',
 'toronto, ottawa, london, auckland/ napier, munich, vancouver, hague, porto & sw england',
 'Faringdon ',
 'Nottinghamshire | London',
 'Cheltenham, England',
 'Dayton, Ohio',
 'Manhattan, NY',
 'Derby, England',
 'Cinderford',
 'Colonia Nervia Glevensium',
 'National',
 '',
 '',
 'Liverpool in Europe',
 'Nottingham, England',
 'West Bridgford Nottingham',
 'Blackheath, London',
 '',
 'England',
 'Birmingham ',
 'Yorkshire, UK',
 'London',
 'USA',
 'all over the place',
 'Rochdale, UK',
 'Sheffield, England',
 'UK',
 "N 52°6' 0'' / W 2°4' 0''",
 'UK',
 'London - NW2',
 'Shrewsbury, Shropshire',
 'Canterbury, UK',
 '',
 'West Yorkshire, uk',
 'Amman',
 'Leicester UK',
 'Long Eaton',
 'Cambridgeshire, UK',
 'Chesterfield, UK',
 'London, UK',
 'INDIA',
 'Scotland',
 'UK',
 'Europe',
 'Salford, Greater Manchester',
 'London',
 'South London',
 '',
 'USA',
 'Wales, United Kingdom',
 'Malvern Hills',
 'European Union',
 'Yorkshire',
 'India',
 'Gloucestershire, UK',
 'Pune, India',
 '',
 'USA',
 'Somewhere under the rainbow ',
 'New York, USA',
 'Babylon The Great, USA',
 'Hong Kong',
 'USA',
 '',
 'USA',
 'Nutley, New Jersey',
 'Bairnsdale East Gippsland',
 'Worldwide',
 'Norman, OK',
 'France',
 'London',
 'country Victoria, Australia',
 'UK',
 '',
 'Vegas Baby!',
 'Brazil',
 'Bristol • Amsterdam • Auvergne',
 'Nottinghamshire, UK',
 '',
 'Bairnsdale East Gippsland',
 'Lincoln, England',
 'Yorkshire & Lincolnshire',
 '',
 'Yorkshire, England',
 'UK, The North',
 'Essex, UK',
 'Earth',
 'redditch',
 '',
 'Milano',
 'Europe and United States',
 'USA',
 'North Norfolk',
 '',
 'Ile-de-France, France',
 'Brussels',
 'UK, The North',
 '',
 'Worcester.',
 'London, England',
 'Raynes Park SW London',
 'Boston, MA',
 'UK ',
 'Bairnsdale East Gippsland',
 'British Columbia, Canada',
 '',
 'USA',
 "Anywhere there's a bar!",
 '',
 'The Vale of Evesham, England',
 '',
 'Manchester, UK',
 '',
 'Russian River',
 'South Jersey ',
 'Worcester',
 '',
 'Cork',
 '',
 'Doncaster Usually',
 '',
 'New York, USA',
 'NY',
 'Canals, rivers and the sea',
 'Walthamstow London England',
 'England',
 'England',
 'Gloucestershire',
 'New York, USA',
 'NY',
 'Worcester',
 'UK',
 '',
 'Gloucestershire',
 'New York, USA',
 'NY',
 'East Devon',
 'Bangkok, Thailand',
 'UK, The North',
 '',
 'Kinshasa',
 'Midlands, UK',
 'Worcester, England',
 '',
 '',
 'UK',
 'Al Hilal - C Ring Road',
 'USA',
 'Worcester, UK',
 'Holmes Chapel, England',
 'UK, The North',
 'Rotherham, England',
 '',
 'Kent, UK',
 'Worcester',
 'No Name, CO',
 'Leicester',
 'UK, The North',
 'Wigan',
 'UK, The North',
 'Jakarta, Indonesia',
 'UK, The North',
 'On the planet some call Earth',
 "Where I go, that's where I am",
 'Brussels',
 'York',
 'Sheffield',
 'London, UK',
 'England',
 'West Midlands',
 'Yorkshire',
 '',
 '',
 'Nigeria',
 'National Capital Region',
 '',
 'USA',
 'West Midlands',
 'Tewkesbury, England, UK',
 'Madison, Wisconsin, USA',
 'London, England',
 'Hove',
 'London',
 'Brussels',
 'East Anglia',
 'European Union',
 'Derby, Derbyshire',
 'Surrey and LB of Croydon',
 'London',
 '',
 'London',
 'England',
 'London/Cambridge',
 'Johannesburg, South Africa',
 'North Tyneside Borough ',
 'A lost soul',
 '',
 '',
 'Lake Arrowhead, California',
 'England, United Kingdom',
 'England, United Kingdom',
 'Melbourne',
 'Unit 1, 64 Wellington Street, Stapleford, Nottingham NG9 7BE',
 'Shireoaks, England',
 'Europe, Planet Earth, normally',
 '',
 'Nottingham\n',
 'England, United Kingdom',
 'Lagos, Nigeria',
 'gloucestershire',
 'Jeddah, Saudi Arabia',
 'India',
 'Wales',
 'Wales',
 'USA',
 'Hell (Tory Britain)',
 'Texas, USA',
 'Earth',
 '',
 'Yorkshire and The Humber, England',
 '',
 'Lagos, Nigeria',
 'Lagos, Nigeria',
 '']

In [2]:
from tqdm import tqdm_notebook

In [ ]:
results = []
for city_name in tqdm_notebook(locations):
    url = f'http://api.openweathermap.org/data/2.5/weather?appid=134666dd0e2cc872e1f9ae630e853b34&units=Imperial&q={city_name}'
    
    try:
        response = r.get(url).json()        
        results.append([response['coord']['lon']], response['coord']['lat'])
    except:
        next

HBox(children=(IntProgress(value=0, max=862), HTML(value='')))

In [8]:
results

[]

In [9]:
city_name = "Oakland, CA"
url = f'http://api.openweathermap.org/data/2.5/weather?appid=134666dd0e2cc872e1f9ae630e853b34&units=Imperial&q='

r.get(url + city_name).json()

{'coord': {'lon': -80.33, 'lat': 43.03},
 'weather': [{'id': 804,
   'main': 'Clouds',
   'description': 'overcast clouds',
   'icon': '04n'}],
 'base': 'stations',
 'main': {'temp': 29.5,
  'pressure': 1011,
  'humidity': 92,
  'temp_min': 27,
  'temp_max': 32},
 'visibility': 24140,
 'wind': {'speed': 6.93, 'deg': 360},
 'clouds': {'all': 90},
 'dt': 1575329747,
 'sys': {'type': 1,
  'id': 818,
  'country': 'CA',
  'sunrise': 1575290038,
  'sunset': 1575323266},
 'timezone': -18000,
 'id': 5907990,
 'name': 'Oakland',
 'cod': 200}